server.port=28080

spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.url=jdbc:hsqldb:hsql://127.0.0.1:29147/calendarAggregator
spring.datasource.username=technical
spring.datasource.password=tgb1q@W3e$R5t
#consilio.hsqldb.start=false

