spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
spring.datasource.url=jdbc:hsqldb:hsql://127.0.0.1:9148/calendarAggregator
spring.datasource.username=technical
spring.datasource.password=...
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HSQLDialect

vaadin.copilot.project-directory=app

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://[::1]:5432/dancemoments
#spring.datasource.username=dancemoments
#spring.datasource.password=dancemoments
#spring.jpa.properties.hibernate.dialect=org.tbee.webstack.postgresql.CustomPostgreSQLDialect
#calendaraggregator.hsqldb.start=false
