#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://172.24.192.1:5432/dancemoments
#spring.datasource.username=dancemoments
#spring.datasource.password=dancemoments
#spring.jpa.properties.hibernate.dialect=org.tbee.webstack.postgresql.CustomPostgreSQLDialect
#consilio.hsqldb.start=false
