name: spotifydanceinfo

services:
  app:
    image: org.tbee.calendaraggregator/calendaraggregator:${PROJECT_VERSION}
    container_name: calendaraggregator
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "5005:5005" # java debug
      - "8080:8080"
    volumes:
      - ./data-volume:/data
    environment:
      BASEURL: http://127.0.0.1:8080
