FROM eclipse-temurin:25-jre-alpine

# Create non-root user (UID/GID 1000) - recommended for security
RUN addgroup -g 1000 appgroup && \
    adduser -D -u 1000 -G appgroup appuser

# Create directories
RUN mkdir -p /app /data && \
    chown -R appuser:appgroup /app /data

# Populate data
COPY --chown=appuser:appgroup --chmod=0644 src/main/container/logback.xml /data/

# Populate app
COPY --chown=appuser:appgroup --chmod=0644 target/*-boot.jar /app/app.jar

# Copy the otel agent
COPY --chown=appuser:appgroup --chmod=0644 target/opentelemetry-javaagent*.jar /app/opentelemetry-javaagent.jar

WORKDIR /data
USER appuser
EXPOSE 8080
EXPOSE 5005

# OpenTelemetry configuration
ENV OTEL_SERVICE_NAME=dancemoments
ENV MANAGEMENT_METRICS_TAGS_APPLICATION=dancemoments
# disable all, this is overridden in the kubernetes deployment
ENV OTEL_LOGS_EXPORTER=none
ENV OTEL_TRACES_EXPORTER=none
ENV OTEL_METRICS_EXPORTER=none

# "-javaagent:/app/opentelemetry-javaagent.jar", this is for spring done by the micrometer-tracing-bridge-otel dependency
ENTRYPOINT ["java", "-Dlogging.config=file:/data/logback.xml", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app/app.jar"]
